export const WI_ICONS = {
  '01d': 'wi wi-day-sunny',
  '01n': 'wi wi-night-clear',
  '02d': 'wi wi-day-sunny-overcast',
  '02n': 'wi wi-night-alt-partly-cloudy',
  '03d': 'wi wi-day-cloudy',
  '03n': 'wi wi-night-alt-cloudy',
  '04d': 'wi wi-day-cloudy-high',
  '04n': 'wi wi-night-alt-cloudy-high',
  '09d': 'wi wi-day-sprinkle',
  '09n': 'wi wi-night-alt-sprinkle',
  '10d': 'wi wi-day-rain',
  '10n': 'wi wi-night-alt-rain',
  '11d': 'wi wi-day-thunderstorm',
  '11n': 'wi wi-night-alt-thunderstorm',
  '13d': 'wi wi-day-snow',
  '13n': 'wi wi-night-alt-snow',
  '50d': 'wi wi-day-fog',
  '50n': 'wi wi-night-fog',
};
